import Navbar from "@/components/Navbar";
import Section from "@/components/Section";
import Footer from "@/components/Footer";
import Link from "next/link";
import { navigationItems } from "@/constants/navigation";

export default function CentreForCredibleAIPage() {
  return (
    <div className="relative min-h-screen bg-white">
      <Navbar items={navigationItems} activeItem="/centre-for-credible-ai" />
      <div className="pt-[64px] md:pt-[80px]">
        <Section className="py-20 md:py-32 lg:py-[180px]">
          <div className="flex flex-col gap-12 md:gap-16 lg:gap-20 items-start max-w-[1200px] mx-auto text-[#001f33]">
            <div className="flex flex-col gap-4 items-start w-full">
              <p className="font-mono text-base md:text-lg font-normal uppercase tracking-[0.32px]">
                project
              </p>
              <h1 className="font-sans text-[28px] sm:text-4xl md:text-[48px] font-normal leading-[1.1] tracking-[-0.56px] sm:tracking-[-0.72px] md:tracking-[-0.96px]">
                Centre for Credible Artificial Intelligence
              </h1>
              <div className="font-mono text-sm md:text-base font-normal leading-[1.4] tracking-[0.16px] max-w-[900px]">
                <p className="mb-4">
                  The Centre was established in connection with the
                  implementation of the project entitled “Centre for Credible
                  Artificial Intelligence”, funded under the International
                  Research Agendas action within the European Funds for Modern
                  Economy (MAB FENG) programme of the Foundation for Polish
                  Science.
                </p>
                <p className="mb-4">
                  The project has received funding in the amount of PLN
                  29,971,105.00 for the period 2025–2029.
                </p>
                <p className="mb-0">
                  Detailed information about the project is available{" "}
                  <Link
                    href="https://credible-ai.org/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline underline-offset-4 hover:opacity-80 transition-opacity"
                  >
                    here
                  </Link>
                  .
                </p>
              </div>
            </div>

            <div className="flex flex-col gap-12 w-full max-w-[900px]">
              <section className="flex flex-col gap-4">
                <h2 className="font-mono text-base md:text-lg font-normal uppercase tracking-[0.32px]">
                  1. Scope of Activities
                </h2>
                <div className="font-mono text-sm md:text-base font-normal leading-[1.6] tracking-[0.16px]">
                  <p className="mb-4">
                    The project focuses on developing new methods for the
                    verification and explanation of artificial intelligence
                    models, with particular emphasis on the technical analysis
                    of their internal mechanisms. The team will develop
                    attribution algorithms for new types of data (time series,
                    biometric data, medical imaging) as well as counterfactual
                    explanation techniques based on generative AI.
                  </p>
                  <p className="mb-4">
                    In parallel, research will address the alignment of AI
                    models with domain knowledge, for example in bioinformatics
                    — verifying whether protein structure prediction models
                    behave in accordance with the laws of biophysics.
                  </p>
                  <p className="mb-0">
                    Complementing the technical core of the project are studies
                    on how individuals and societies respond to AI systems —
                    ranging from user trust analysis to modeling phenomena such
                    as information overload and the spread of misinformation
                    generated by large language models.
                  </p>
                </div>
              </section>

              <section className="flex flex-col gap-4">
                <h2 className="font-mono text-base md:text-lg font-normal uppercase tracking-[0.32px]">
                  2. Target Groups
                </h2>
                <div className="font-mono text-sm md:text-base font-normal leading-[1.6] tracking-[0.16px]">
                  <p className="mb-4">
                    The project is addressed to three main stakeholder groups:
                  </p>
                  <ul className="list-disc pl-5 flex flex-col gap-2">
                    <li>
                      The scientific community, which applies AI models in
                      research and requires robust verification tools.
                    </li>
                    <li>
                      Companies and organizations deploying AI-based solutions,
                      seeking to enhance the safety and credibility of their
                      systems (e.g., in medicine, the space industry, or
                      finance).
                    </li>
                    <li>
                      Society at large, which will benefit indirectly through
                      increased transparency of widely used AI models, reduced
                      misinformation, and improved digital literacy.
                    </li>
                  </ul>
                </div>
              </section>

              <section className="flex flex-col gap-4">
                <h2 className="font-mono text-base md:text-lg font-normal uppercase tracking-[0.32px]">
                  3. Project Objectives
                </h2>
                <div className="font-mono text-sm md:text-base font-normal leading-[1.6] tracking-[0.16px]">
                  <p className="mb-4">
                    The primary objective is to establish and develop a
                    research and implementation unit dedicated to AI model
                    verification, whose long-term sustainability will be
                    ensured through collaboration with EU industry partners and
                    research institutions worldwide.
                  </p>
                  <p className="mb-4">
                    The Centre for Credible AI aims to achieve qualitative
                    progress in the verifiability of AI systems in terms of
                    safety, transparency, and controllability. In particular,
                    the Centre will:
                  </p>
                  <ul className="list-disc pl-5 flex flex-col gap-2">
                    <li>
                      Propose new methods for validation and knowledge
                      extraction from AI models, including foundation models.
                    </li>
                    <li>
                      Advance these methods toward practical applications and
                      commercialization, offering a complete value chain of
                      competencies.
                    </li>
                    <li>
                      Develop standards, recommendations, and best practices
                      for AI model auditing for the business sector in Poland
                      and globally.
                    </li>
                  </ul>
                </div>
              </section>

              <section className="flex flex-col gap-4">
                <h2 className="font-mono text-base md:text-lg font-normal uppercase tracking-[0.32px]">
                  4. Expected Outcomes
                </h2>
                <div className="font-mono text-sm md:text-base font-normal leading-[1.6] tracking-[0.16px]">
                  <p className="mb-3">The project will deliver multiple outcomes:</p>
                  <p className="mb-2">For science:</p>
                  <ul className="list-disc pl-5 flex flex-col gap-2 mb-4">
                    <li>
                      New methods and tools for explaining and validating AI
                      models (attribution methods, counterfactual explanations,
                      bioinformatics model verification techniques).
                    </li>
                    <li>Publications in leading international journals and conferences.</li>
                    <li>
                      Scientific discoveries in medicine, biology, and physics
                      supported by explainable AI methods.
                    </li>
                  </ul>
                  <p className="mb-2">For business and AI implementers:</p>
                  <ul className="list-disc pl-5 flex flex-col gap-2 mb-4">
                    <li>Commercializable AI auditing and verification tools.</li>
                    <li>
                      Standards and best practices aligned with the EU AI Act
                      requirements.
                    </li>
                    <li>
                      Concrete implementations in cooperation with partners
                      such as the European Space Agency (ESA).
                    </li>
                  </ul>
                  <p className="mb-2">For society:</p>
                  <ul className="list-disc pl-5 flex flex-col gap-2">
                    <li>
                      An independent observatory monitoring the safety and
                      transparency of widely used AI systems, including large
                      language models.
                    </li>
                    <li>
                      Mitigation of risks such as deepfakes, misinformation,
                      and algorithmic bias.
                    </li>
                    <li>
                      Increased digital competencies and strengthened national
                      cybersecurity.
                    </li>
                  </ul>
                </div>
              </section>

              <section className="flex flex-col gap-4">
                <h2 className="font-mono text-base md:text-lg font-normal uppercase tracking-[0.32px]">
                  5. Project Value
                </h2>
                <div className="font-mono text-sm md:text-base font-normal leading-[1.6] tracking-[0.16px]">
                  <ul className="list-disc pl-5 flex flex-col gap-2">
                    <li>Total project cost: PLN 29,971,105.00</li>
                    <li>EU Funds contribution: PLN 29,971,105.00</li>
                  </ul>
                  <p className="mt-4 mb-0">#EUFunds #EuropeanFunds</p>
                </div>
              </section>
            </div>
          </div>
        </Section>
      </div>
      <Footer />
    </div>
  );
}

